name: Cycle Through Images in README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  rotate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "eugene4545"
          git config --global user.email "eugeneonuoha72@gmail.com"

      - name: List SVG Images
        run: |
          echo "Listing SVG images in the 'images' folder:"
          ls images/*.svg

      - name: Rotate Image
        run: |
          images=($(ls images/*.svg))
          if [ ${#images[@]} -eq 0 ]; then
            echo "No SVG images found."
            exit 1
          fi
          if [ -f image_index.txt ]; then
            index=$(cat image_index.txt)
          else
            index=0
          fi
          index=$(( (index + 1) % ${#images[@]} ))
          next_image=${images[$index]}
          echo "Images array: ${images[@]}"
          echo "Index: $index"
          echo "Next image: $next_image"
          sed -i "s|<img align=\"right\" style=\"width: 400px; margin-right: 10px;\" src=\"images/.*\"|<img align=\"right\" style=\"width: 400px; margin-right: 10px;\" src=\"$next_image\"|g" README.md
          echo $index > image_index.txt

      - name: Commit and Push Changes
        run: |
          next_image_basename=$(basename "$next_image")
          git add README.md image_index.txt
          git commit -m "Rotate image to $next_image_basename"
          git push
        env:
          CYCLE_TOKEN: ${{ secrets.CYCLE_TOKEN }}
