name: Cycle Through Images in README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  rotate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "eugene4545"
          git config --global user.email "eugeneonuoha72@gmail.com"

      - name: List SVG Images
        run: |
          # List SVG images
          echo "Listing SVG images in the 'images' folder:"
          ls images/*.svg

      - name: Rotate Image
        run: |
          # Initialize images array
          images=($(ls images/*.svg))

          # Debugging - Check if image_index.txt exists and read the index
          if [ -f image_index.txt ]; then
            index=$(cat image_index.txt)
          else
            index=0
          fi
          echo "Current index: $index"

          # Calculate the new index
          index=$(( (index + 1) % ${#images[@]} ))
          next_image=${images[$index]}

          # Debugging - Output next image and new index
          echo "Next image: $next_image"
          echo "New index: $index"

          # Save the new index to image_index.txt
          echo $index > image_index.txt

          # Debugging - Print README before modification
          echo "Before modification:"
          cat README.md

          # Modify the README to update the image source
          sed -i "s|<img align=\"right\" style=\"width: 400px; margin-right: 10px;\" src=\"images/.*\"|<img align=\"right\" style=\"width: 400px; margin-right: 10px;\" src=\"$next_image\"|g" README.md

          # Debugging - Print README after modification
          echo "After modification:"
          cat README.md

      - name: Commit Changes
        run: |
          # Commit the updated README and index file
          git add README.md image_index.txt
          git commit -m "Update image in README to $(basename "$next_image")"
          git push
        env:
          CYCLE_TOKEN: ${{ secrets.CYCLE_TOKEN }}
