name: Cycle Through Images in README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  rotate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "eugene4545"
          git config --global user.email "eugeneonuoha72@gmail.com"

      - name: Rotate Image
        run: |
          # Get a list of all image files in the images folder
          images=($(ls images/*))

          # Debugging
          echo "Images found: ${images[@]}"

          # Check if there are any images
          if [ ${#images[@]} -eq 0 ]; then
            echo "No images found."
            exit 1
          fi

          # Read the current image index from a file, or start at 0 if the file doesn't exist
          if [ -f image_index.txt ]; then
            index=$(cat image_index.txt)
          else
            index=0
          fi

          # Increment the index, wrapping around if necessary
          index=$(( (index + 1) % ${#images[@]} ))

          # Get the next image based on the updated index
          next_image=${images[$index]}

          # Debugging
          echo "Next image: $next_image"
          echo "Current index: $index"

          # Print README.md before modification
          echo "Before modification:"
          cat README.md

          # Update the README.md file to point to the next image
          sed -i "s|<img align=\"right\" style=\"width: 400px; margin-right: 10px;\" src=\"images/.*\"|<img align=\"right\" style=\"width: 400px; margin-right: 10px;\" src=\"$next_image\"|g" README.md

          # Print README.md after modification
          echo "After modification:"
          cat README.md

          # Save the new index for the next run
          echo $index > image_index.txt

      - name: Commit and Push Changes
        run: |
          git add README.md image_index.txt
          git commit -m "Rotate image to $(basename $next_image)"
          git push
        env:
          CYCLE_TOKEN: ${{ secrets.CYCLE_TOKEN }}
