name: Cycle Through Images in README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  rotate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "eugene4545"
          git config --global user.email "eugeneonuoha72@gmail.com"

      - name: List SVG Images
        run: |
          # List SVG images
          echo "Listing SVG images in the 'images' folder:"
          ls images/*.svg

      # Debugging step to print images array
      - name: Debug Images Array
        run: |
          images=($(ls images/*.svg))
          echo "Images found: ${images[@]}"
          echo "Number of images: ${#images[@]}"

      - name: Rotate Image
        run: |
          # More debugging steps to check the value of variables
          if [ -f image_index.txt ]; then
            index=$(cat image_index.txt)
          else
            index=0
          fi
          echo "Current index: $index"

          index=$(( (index + 1) % ${#images[@]} ))
          next_image=${images[$index]}

          echo "Next image: $next_image"
          echo "New index: $index"

          # Debugging - Print README before modification
          echo "Before modification:"
          cat README.md

          # Modify the README
          sed -i "s|<img align=\"right\" style=\"width: 400px; margin-right: 10px;\" src=\"images/.*\"|<img align=\"right\" style=\"width: 400px; margin-right: 10px;\" src=\"$next_image\"|g" README.md

          # Debugging - Print README after modification
          echo "After modification:"
          cat README.md

      # Debugging step to check commit details
      - name: Debug Commit Message
        run: |
          next_image_basename=$(basename "$next_image")
          echo "Committing image: $next_image_basename"
